name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Run shellcheck
        run: shellcheck *.sh
